/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ExceptionPage: typeof import('./components/ExceptionPage/index.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconButton: typeof import('./components/IconButton/index.vue')['default']
    IconCustomNoPermission: typeof import('~icons/custom/no-permission')['default']
    IconCustomNotFound: typeof import('~icons/custom/not-found')['default']
    IconCustomServiceError: typeof import('~icons/custom/service-error')['default']
    IconCustomSideMenu: typeof import('~icons/custom/side-menu')['default']
    IconCustomTopMenu: typeof import('~icons/custom/top-menu')['default']
    'IconEp:arrowDown': typeof import('~icons/ep/arrow-down')['default']
    IconEpEdit: typeof import('~icons/ep/edit')['default']
    IconEpSetting: typeof import('~icons/ep/setting')['default']
    IconEpStar: typeof import('~icons/ep/star')['default']
    'IconLineMd:menuFoldLeft': typeof import('~icons/line-md/menu-fold-left')['default']
    'IconLineMd:menuFoldRight': typeof import('~icons/line-md/menu-fold-right')['default']
    'IconMdi:alphaACircle': typeof import('~icons/mdi/alpha-a-circle')['default']
    'IconMdi:language': typeof import('~icons/mdi/language')['default']
    'IconMdi:theme': typeof import('~icons/mdi/theme')['default']
    'IconMdi:weatherNight': typeof import('~icons/mdi/weather-night')['default']
    'IconMdi:weatherSunny': typeof import('~icons/mdi/weather-sunny')['default']
    'IconRi:fullscreenExitFill': typeof import('~icons/ri/fullscreen-exit-fill')['default']
    'IconRi:fullscreenFill': typeof import('~icons/ri/fullscreen-fill')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    MessageBoxDemo: typeof import('./components/MessageBoxDemo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
